### ISSUE TITLE
upsidedownternet not working

### ISSUE THREAD

**Issue by jevb** [byt3bl33d3r/MITMf#307]
getting this error when trying to use upsidedownternet

`Error: 'Upsidedownternet' object has no attribute 'imagetype'`

**Comment by prairie-guy** [comment]
Same problem here. I am running on NetHunter Kali. I just upgraded to 0.9.8. Upsidedownternet worked fine on 0.9.7, but returns the imagetype error described by jevb in 0.9.8.

**Comment by byt3bl33d3r** [comment]
Resolved in 2dc1dd4f1260c34d168d25c0b387980ca3a2b247
